#!/usr/bin/env bash

set -Eeuxo pipefail

docker build --build-arg NPROC="$NPROC" -t wilsonzlin/timescale-rum:latest -t wilsonzlin/timescale-rum:$(jq -r .pg ./versions.json)-$(jq -r .rum ./versions.json)-$(jq -r .ts ./versions.json) --progress plain .
