#!/usr/bin/env bash

set -Eeuxo pipefail

pushd "$(dirname "$0")" >/dev/null

wget -O pg.tar.gz 'https://ftp.postgresql.org/pub/source/v14.1/postgresql-14.1.tar.bz2'
wget -O rum.tar.gz 'https://github.com/postgrespro/rum/archive/refs/tags/1.3.9.tar.gz'
wget -O ts.tar.gz 'https://github.com/timescale/timescaledb/archive/refs/tags/2.5.1.tar.gz'

popd >/dev/null
